package independent_test

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"maps"
	"reflect"
	"strings"
	"testing"
	"time"
)

const nfdumpTimeLayout = "2006-01-02T15:04:05.000"

// Literal canonical values plus the pinned nfdump 1.7.9 conversion rules.
// NDJSON does not preserve original sequences/templates, ordinary IE 34, or
// arbitrary enterprise data. The retained stream/goldens check those bytes.
func nfdumpProjection(protocol string, tc fixtureCase, stream []exportPacket) []map[string]any {
	var rows []map[string]any
	for _, packet := range stream {
		if packet.phase != "data" {
			continue
		}
		for range tc.ExpectedRecords {
			row := map[string]any{
				"cnt": jsonNum(len(rows) + 1), "type": "FLOW", "ident": "otel-netflow",
				"export_sysid": jsonNum(1), "ip4_router": "127.0.0.1", "tcp_flags": "...AP...",
				"proto": jsonNum(6), "src_port": jsonNum(12345), "dst_port": jsonNum(443),
				"fwd_status": jsonNum(0), "src_tos": jsonNum(0), "dst_tos": jsonNum(0), "direction": jsonNum(0),
				"input_snmp": jsonNum(10), "output_snmp": jsonNum(20),
				"src_as": jsonNum(64513), "dst_as": jsonNum(64514),
				"in_packets": jsonNum(1234), "in_bytes": jsonNum(56789), "sampled": jsonNum(0),
				"first": "1970-01-01T00:00:00.000", "last": "1970-01-01T00:00:00.000",
			}
			ipv6 := strings.Contains(tc.Name, "ipv6")
			if ipv6 {
				row["src6_addr"], row["dst6_addr"] = "2001:db8::1", "2001:db8::2"
				row["src6_geo"], row["dst6_geo"] = "", ""
				row["src_mask"], row["dst_mask"] = jsonNum(64), jsonNum(64)
				row["src_net"], row["dst_net"] = "2001:db8::", "2001:db8::"
			} else {
				row["src4_addr"], row["dst4_addr"] = "192.0.2.1", "198.51.100.2"
				row["src4_geo"], row["dst4_geo"] = "", ""
				row["src_mask"], row["dst_mask"] = jsonNum(24), jsonNum(24)
				row["src_net"], row["dst_net"] = "192.0.2.0", "198.51.100.0"
			}
			if protocol == "v5" {
				row["in_packets"], row["in_bytes"], row["sampled"] = jsonNum(1234000), jsonNum(56789000), jsonNum(1)
				row["ip4_next_hop"] = "192.0.2.254"
				// Process_v5 fills only interfaces in EXflowMisc. Although the
				// wire carries /24 masks, this release never copies those bytes.
				row["src_mask"], row["dst_mask"] = jsonNum(0), jsonNum(0)
				row["src_net"], row["dst_net"] = "", ""
				p := packet.bytes
				exported := uint64(binary.BigEndian.Uint32(p[8:]))*1000 + uint64(binary.BigEndian.Uint32(p[12:]))/1_000_000
				origin := exported - uint64(binary.BigEndian.Uint32(p[4:]))
				row["first"] = time.UnixMilli(int64(origin + 1000)).UTC().Format(nfdumpTimeLayout)
				row["last"] = time.UnixMilli(int64(origin + 1001)).UTC().Format(nfdumpTimeLayout)
			} else {
				row["ip_minttl"], row["ip_maxttl"] = jsonNum(64), jsonNum(0)
				row["ip_version"] = jsonNum(4)
				if ipv6 {
					row["ip_version"] = jsonNum(6)
				}
				// IE 60 selects the layer2 extension; its other fields are zero.
				for _, key := range []string{"vlanID", "post_vlanID", "cust_vlanID", "post_cust_vlanID", "phys_ingress", "phys_egress", "ethertype"} {
					row[key] = jsonNum(0)
				}
			}
			if protocol == "ipfix" {
				// NTP64ToMilliseconds floors the binary fraction, including the
				// canonical encoded end one nanosecond below the +1 ms boundary.
				row["first"], row["last"] = "2026-09-01T00:00:01.000", "2026-09-01T00:00:01.000"
			} else if protocol == "ipfix-general" {
				row["first"], row["last"] = "2026-09-01T00:00:00.123", "2026-09-01T00:00:01.123"
			}
			rows = append(rows, row)
		}
	}
	return rows
}

func compareNfdumpRows(got, want []map[string]any, earliest, latest time.Time) error {
	if len(got) != len(want) {
		return fmt.Errorf("nfdump rows=%d, want %d", len(got), len(want))
	}
	for i, row := range got {
		// Arrival time is newly generated by the receiver. Require the exact
		// type/UTC format and a timestamp inside this run, never copy it into
		// expected values or silently discard an arbitrary dynamic field.
		received, ok := row["received"].(string)
		stamp, err := time.Parse(nfdumpTimeLayout, received)
		if !ok || err != nil || stamp.Format(nfdumpTimeLayout) != received || stamp.Before(earliest) || stamp.After(latest) {
			return fmt.Errorf("row %d invalid arrival timestamp: %v", i, row["received"])
		}
		stable := maps.Clone(row)
		delete(stable, "received")
		if !reflect.DeepEqual(stable, want[i]) {
			return fmt.Errorf("nfdump row %d:\n got %#v\nwant %#v", i, stable, want[i])
		}
	}
	return nil
}

func TestNfdumpOutputValidation(t *testing.T) {
	// Failure cases include receiver conversion losses and dynamic arrival
	// timestamps. They run without installing any external decoder.
	want := nfdumpProjection("ipfix", fixtureCase{Name: "canonical-ipv4", ExpectedRecords: 1}, []exportPacket{{phase: "data"}})
	row := maps.Clone(want[0])
	row["received"] = "2026-09-07T12:00:00.123"
	data, err := json.Marshal(row)
	must(t, err)
	valid := append(data, '\n')
	start := time.Date(2026, 9, 7, 12, 0, 0, 0, time.UTC)
	for _, tc := range []struct {
		name   string
		mutate func([]map[string]any) []map[string]any
	}{
		{"correct", func(r []map[string]any) []map[string]any { return r }},
		{"missing", func(r []map[string]any) []map[string]any { return nil }},
		{"duplicate", func(r []map[string]any) []map[string]any { return append(r, r[0]) }},
		{"type", func(r []map[string]any) []map[string]any { r[0]["in_bytes"] = "56789"; return r }},
		{"scaling", func(r []map[string]any) []map[string]any { r[0]["in_packets"] = jsonNum(1234000); return r }},
		{"sampled", func(r []map[string]any) []map[string]any { r[0]["sampled"] = jsonNum(1); return r }},
		{"time", func(r []map[string]any) []map[string]any { r[0]["last"] = "2026-09-01T00:00:01.001"; return r }},
		{"family", func(r []map[string]any) []map[string]any { r[0]["ip_version"] = jsonNum(6); return r }},
		{"ttl", func(r []map[string]any) []map[string]any { r[0]["ip_minttl"] = jsonNum(0); return r }},
		{"address", func(r []map[string]any) []map[string]any { r[0]["src4_addr"] = "192.0.2.2"; return r }},
		{"field-missing", func(r []map[string]any) []map[string]any { delete(r[0], "src_as"); return r }},
		{"enterprise-unexpected", func(r []map[string]any) []map[string]any { r[0]["en32473:id401"] = "0x000102"; return r }},
		{"arrival-missing", func(r []map[string]any) []map[string]any { delete(r[0], "received"); return r }},
		{"arrival-type", func(r []map[string]any) []map[string]any { r[0]["received"] = jsonNum(0); return r }},
		{"arrival-invalid", func(r []map[string]any) []map[string]any { r[0]["received"] = "invalid"; return r }},
		{"arrival-before", func(r []map[string]any) []map[string]any { r[0]["received"] = "2026-09-07T11:59:59.999"; return r }},
		{"arrival-after", func(r []map[string]any) []map[string]any { r[0]["received"] = "2026-09-07T12:00:01.001"; return r }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseRows(valid, true)
			must(t, err)
			err = compareNfdumpRows(tc.mutate(got), want, start, start.Add(time.Second))
			if (err == nil) != (tc.name == "correct") {
				t.Fatalf("unexpected validation result: %v", err)
			}
		})
	}
}
