// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/pocket-grimoire-guild/otelcol-exporter-netflow/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.NetflowExporterAdmission.Add(context.Background(), 1)
	tb.NetflowExporterBytes.Add(context.Background(), 1)
	tb.NetflowExporterDataMessages.Add(context.Background(), 1)
	tb.NetflowExporterDNS.Add(context.Background(), 1)
	tb.NetflowExporterEndpointEpochs.Add(context.Background(), 1)
	tb.NetflowExporterFailures.Add(context.Background(), 1)
	tb.NetflowExporterLosses.Add(context.Background(), 1)
	tb.NetflowExporterRecords.Add(context.Background(), 1)
	tb.NetflowExporterTemplates.Add(context.Background(), 1)
	AssertEqualNetflowExporterAdmission(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterBytes(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterDataMessages(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterDNS(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterEndpointEpochs(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterFailures(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterLosses(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterRecords(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualNetflowExporterTemplates(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
