// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the exporter/netflow component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("netflow")
	ScopeName = "github.com/pocket-grimoire-guild/otelcol-exporter-netflow"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
