// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/pocket-grimoire-guild/otelcol-exporter-netflow")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/pocket-grimoire-guild/otelcol-exporter-netflow")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                         metric.Meter
	mu                            sync.Mutex
	registrations                 []metric.Registration
	NetflowExporterAdmission      metric.Int64Counter
	NetflowExporterBytes          metric.Int64Counter
	NetflowExporterDataMessages   metric.Int64Counter
	NetflowExporterDNS            metric.Int64Counter
	NetflowExporterEndpointEpochs metric.Int64Counter
	NetflowExporterFailures       metric.Int64Counter
	NetflowExporterLosses         metric.Int64Counter
	NetflowExporterRecords        metric.Int64Counter
	NetflowExporterTemplates      metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.NetflowExporterAdmission, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.admission",
		metric.WithDescription("Whole requests by admission result before helper entry. Accepted does not imply a write. [Alpha]"),
		metric.WithUnit("{request}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterBytes, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.bytes",
		metric.WithDescription("Intended UDP payload bytes by local handoff result. Ambiguous counts the complete datagram, not the returned write length. [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterDataMessages, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.data_messages",
		metric.WithDescription("Data datagrams classified by local UDP handoff result. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterDNS, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.dns",
		metric.WithDescription("Hostname resolution attempts by validated result, independently of later dial or bootstrap failures. Literal endpoints are excluded. [Alpha]"),
		metric.WithUnit("{lookup}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterEndpointEpochs, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.endpoint_epochs",
		metric.WithDescription("Fully bootstrapped endpoint publications, including the initial epoch. [Alpha]"),
		metric.WithUnit("{epoch}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterFailures, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.failures",
		metric.WithDescription("Failed operations by fixed reason. A request or candidate may fail more than one operation. [Alpha]"),
		metric.WithUnit("{event}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterLosses, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.losses",
		metric.WithDescription("Explicitly acknowledged mapping loss events. [Alpha]"),
		metric.WithUnit("{event}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterRecords, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.records",
		metric.WithDescription("Flow records classified by local UDP handoff result. [Alpha]"),
		metric.WithUnit("{record}"),
	)
	errs = errors.Join(errs, err)
	builder.NetflowExporterTemplates, err = builder.meter.Int64Counter(
		"otelcol_netflow.exporter.templates",
		metric.WithDescription("Template datagrams by bootstrap or refresh handoff result, including unpublished candidate writes. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
